### PR TITLE
Added non-blocking and sound queue

### PR DESCRIPTION
**Pull request by Defragster**
Edits to Talkie.cpp and .h and keywords.txt :: Removed the delay(25) from .say using .sayQ

Called it sayQ() because I added a 24 sound queue managed in the code so not one but 25 sounds can be pushed into a queue for playing sequentially without user attention or delay.

.active() - is **false** on silence, else **returns count** of sounds yet to play
.sayQ() - returns the space left in queue
.sayQ(0) empties the que and stops audio out
.say(0) empties the que and stops audio out
.say() is otherwise 'unchanged' - it will block [until the queue empties]

Added example of all methods: SayQAcorn.ino 
Core Talkie code unchanged, except for cascaded timer to update synthesis data

### CODE REVIEW

**Comment by Defragster** [comment]
I'm done editing my edits - AFAIK this Talkie library and my changes are ready for immediate release and it works with the Prop Shield. You might want to refine the 'core Talkie' synthesis in future - but it is working entertainingly well.

**Comment by PaulStoffregen** [comment]
Looking at this now... for the first time.

What happened to the large vocab example?

**Comment by Defragster** [comment]
Paul - sync again please - I used EXAMPLES as a testing work area for others.  I restored all original examples, added the last one "SayQAcorn" that shows all new utility/methods I added - moved my extra examples to SayQ_extra - you can prune that if you want.

**Comment by PaulStoffregen** [comment]
Looks like the original Talkie is no longer being maintained.  I wanted to give Peter time to merge my AVR friendly changes that didn't edit much of the code.  But it looks like that's never going to happen, so time to move forward.

I haven't really had time to review this... but I'm going to merge it all now, since I need to publish Teensyduino 1.28-beta2 soon and I really want this to be in it.  :)

**Comment by Defragster** [comment]
Awesome! I wanted it to be included in 1.28 too.  I didn't try it on an UNO or anything - it would be easy to #ifdef original .say() method back in - but my work left that pushed to the new timer sharing scheme that will likely 'stutter' on a weaker processor as the data update will put off the next timer interrupt. It was tested to work on an LC and T_3.2 at 24MHz.

**Pull request merged**
