### PR TITLE
Updated Talkie library to single Begin Statement

### PR DESCRIPTION
**Pull request by mjs513**
In discussions on the Talkie thread, https://forum.pjrc.com/threads/33446-Talkie-speech-library?p=221362&viewfull=1#post221362, and a few about.  Figured it was time to update the library to something simplier to use - a single begin statement:
1.  If voice.begin() will default to DAC if available and you can use the propshield in the normal way,
2.  If you do voice.begin(xx) where xx is any pwm pin it will use PWM signals.

Think this may be better.  I did test it with a Propshield on a t3.5 and the T4.

### CODE REVIEW

**Review by Defragster — CHANGES_REQUESTED** [review]
In the talkie.cpp declaration if defaulted to :: _hasPShield = true;

It would work with default pins when .begin() not called.  It seems not all examples show use of .begin()?

Current is : _hasPShield = false;

**Comment by mjs513** [comment]
@Defragster 
Made a couple of other changes as well as defaulting to true for _hasPropShield other wise you would be stuck having to use begin(pwmPin) constructor.  Now for the T4 if no begin is used it defaults to pin A0 unless you specify another pin.

**Comment by Defragster** [comment]
Okay, I was looking at the change - while on the phone.  Just scanned the readme - the only indication of a 'default' pin is for #3: 
"Important facts
LPC currently outputs speech sounds on digital pin 3 only. "

And the case in the code does hardcoded: pinMode(5, OUTPUT);

Not sure if pin 3 or 5 makes more sense than A0 for expected default?

**Comment by mjs513** [comment]
Changed the default pin for the T4.x to use pin 5 and took a crack at updating the README.

**Review by Defragster — APPROVED** [review]

**Comment by PaulStoffregen** [comment]
Will this change break existing projects which call beginPWM()?

**Comment by mjs513** [comment]
Unfortunately yes.   If you would prefer it would be easy enough to add in a separate call to beginPWM as an alternate to avoid the conflict.

**Comment by PaulStoffregen** [comment]
Yes, please add a beginPWM() function.  An inline function within the class definition in the header file is perfectly fine.  I want to minimize breakage of programs people have already written.

**Comment by PaulStoffregen** [comment]
Maybe also add a comment with that inline function, advising to use the simpler begin(), but the old is being kept only for backwards compatibility with existing programs.

**Comment by mjs513** [comment]
Ok.  All done.  Added the beginPWM function back in for backwards compatibility.  Tested it out on T4 only since it just call the begin function :).

**Pull request merged**
